### ISSUE TITLE
Fresh clone in RPI 4 can't install: make: *** No rule to make target...

### ISSUE THREAD

**Issue by notbrain** [alexeden/rpi-led-matrix#12]
Apologies if this is too obvious, but I did a brand new clone on an RPI 4 I just received, and I encounter this on `npm install`. I saw the RPI 3B+ closed issue and saw support for RPI 4 should be here, but wondering if I am missing any configuration or dependencies that would help me get past this, or if builds for this arch aren't yet available.

Thanks! 

```
$ npm i

> nodemon@1.18.10 postinstall /home/pi/src/rpi-led-matrix/node_modules/nodemon
> node bin/postinstall || exit 0


> rpi-led-matrix@1.10.0 install /home/pi/src/rpi-led-matrix
> node-gyp rebuild

make: Entering directory '/home/pi/src/rpi-led-matrix/build'
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/src/nothing.o
  AR(target) Release/obj.target/node_modules/node-addon-api/src/nothing.a
  COPY Release/nothing.a
make: *** No rule to make target 'Release/obj.target/vendor/vendor/lib/thread.o', needed by 'Release/obj.target/vendor.a'.  Stop.
make: Leaving directory '/home/pi/src/rpi-led-matrix/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/nodejs/node-v12.18.2-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.118-v7l+
gyp ERR! command "/usr/local/lib/nodejs/node-v12.18.2-linux-armv7l/bin/node" "/usr/local/lib/nodejs/node-v12.18.2-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/src/rpi-led-matrix
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rpi-led-matrix@1.10.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rpi-led-matrix@1.10.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-07-19T14_41_21_236Z-debug.log
```

**Comment by alexeden** [comment]
Hi @notbrain, make sure you include the recurse-submodules flag [when you get the repo](https://github.com/alexeden/rpi-led-matrix#developing-locally):

```
$ git clone --recurse-submodules https://github.com/alexeden/rpi-led-matrix
```

Let me know if that fixes it.

**Comment by alexeden** [comment]
Closing this because I'm _mostly_ sure that that's the issue. I've accidentally forgotten the flag many times myself and saw the same thing. Let me know if not!

**Comment by notbrain** [comment]
Thanks! I think that did it. Doh!
