### ISSUE TITLE
`npm install` will fail on mac OS

### ISSUE THREAD

**Issue by pedrosimao** [alexeden/rpi-led-matrix#2]
I get an error when trying to run `npm install` after `git clone`. I am trying to use the suggested `sync` workflow. I have tried with `yarn install` and I have the same problem. Here is my error output: 
```
TypeError: cannot use a string pattern on a bytes-like object
make: *** [Release/nothing.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/pedro1/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/pedro1/.nvm/versions/node/v10.15.0/bin/node" "/Users/pedro1/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pedro1/Documents/MY_DOCUMENTS/HOT_DOCUMENTS/--CODE--/GITHUB/msa-led-counter
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
```

Am I missing something?

**Comment by pedrosimao** [comment]
Ok, I have found the solution.
I was running it on python 3 environment. I switched my env to python 2.7 and now I got it working.
Maybe that should be mentioned in the documentation?

**Comment by alexeden** [comment]
Interesting. I'll add a note to the documentation here shortly. Thanks!
